limit_req_zone $binary_remote_addr zone=littletask_general:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=littletask_upload:10m rate=30r/m;
limit_req_zone $binary_remote_addr zone=littletask_registration:10m rate=20r/m;
limit_conn_zone $binary_remote_addr zone=littletask_connections:10m;
